apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd # Namespace where the Argo CD control plane is running
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD # Targets the latest commit on the default branch
    path: guestbook # Directory path within the repository
  destination:
    server: https://kubernetes.default.svc # The target Kubernetes cluster API server
    namespace: guestbook # The target namespace within the cluster
