apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd # Namespace where the Argo CD control plane is running
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/raheemsRandy/eks-argocd.git
    targetRevision: main # Targets the latest commit on the default branch
    path: storageclasses # Directory path within the repository
  destination:
    server: https://kubernetes.default.svc # The target Kubernetes cluster API server
    namespace: argocd # The target namespace within the cluster
  syncPolicy:
    automated: # Enable automated synchronization
      prune: true # Delete resources that are no longer in Git
      selfHeal: true # Revert changes made manually in the cluster to match Git
    syncOptions:
      - CreateNamespace=true # Automatically create the target namespace if it doesn't exist
